---
fixtures:
  repositories:
    augeas_core:
      repo: 'https://github.com/simp/pupmod-puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    firewalld:
      repo: https://github.com/simp/pupmod-voxpupuli-firewalld
      ref: v4.3.0
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    iptables: "#{source_dir}"
