---
fixtures:
  repositories:
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    compliance: "https://github.com/trevor-vaughan/pupmod-compliance
  symlinks:
    iptables: "#{source_dir}"
