HOSTS:
  el7:
    roles:
      - server7
      - default
    platform: el-7-x86_64
    box :     centos/7
    hypervisor : vagrant

  el6:
    roles:
      - server6
    platform: el-6-x86_64
    box :     centos/6
    hypervisor : vagrant
CONFIG:
  type: aio
  log_level: verbose
  vagrant_memsize: 256
